steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/paulo-actualbudget/actualbudget", "."]
  entrypoint: "docker"
logsBucket: 'gs://paulo-actualbudget-cloudbuild-logs'
serviceAccount: 'projects/paulo-actualbudget/serviceAccounts/cloud-build-service-account@paulo-actualbudget.iam.gserviceaccount.com'
options:
  logging: GCS_ONLY