logsBucket: 'gs://paulo-actualbudget-cloudbuild-logs'
serviceAccount: 'projects/paulo-actualbudget/serviceAccounts/cloud-build-service-account@paulo-actualbudget.iam.gserviceaccount.com'
options:
  logging: GCS_ONLY